CREATE TABLE [dbo].[Table]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [NAME] VARCHAR(50) NULL, 
    [PRICE] INT NULL, 
    [STOCK] INT NULL, 
    [UNIT] INT NULL, 
    [CATEGORY] VARCHAR(50) NULL,
)
